# Generated by Django 4.1.2 on 2022-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Delete at'),
        ),
    ]
