# Generated by Django 4.1.1 on 2022-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_conversations_model_userprofile_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations_model',
            name='sender_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
